// This file is automatically generated. Do not modify it manually.

package main

import (
	"strings"

	"encoding/json"
	"github.com/mattermost/mattermost-server/v6/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "com.mattermost.matterless-plugin",
  "name": "Matterless plugin",
  "description": "This plugin hosts Matterless as a Mattermost plugin",
  "homepage_url": "https://github.com/zefhemel/mattermost-matterless-plugin",
  "support_url": "https://github.com/zefhemel/mattermost-matterless-plugin/issues",
  "release_notes_url": "https://github.com/zefhemel/mattermost-matterless-plugin/releases",
  "icon_path": "assets/starter-template-icon.svg",
  "version": "0.1.0",
  "min_server_version": "5.12.0",
  "server": {
    "executables": {
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "darwin-arm64": "server/dist/plugin-darwin-arm64",
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "linux-arm64": "server/dist/plugin-linux-arm64"
    },
    "executable": ""
  },
  "settings_schema": {
    "header": "Matterless",
    "footer": "",
    "settings": [
      {
        "key": "DataDir",
        "display_name": "Data directory:",
        "type": "text",
        "help_text": "The path to the folder to keep state",
        "placeholder": "",
        "default": "./mls-data"
      },
      {
        "key": "NatsURL",
        "display_name": "URL to NATS for clustering:",
        "type": "text",
        "help_text": "",
        "placeholder": "",
        "default": "nats://localhost:4222"
      },
      {
        "key": "AdminToken",
        "display_name": "Admin token:",
        "type": "generated",
        "help_text": "Admin token to use",
        "placeholder": "",
        "default": null
      }
    ]
  }
}
`

func init() {
	_ = json.NewDecoder(strings.NewReader(manifestStr)).Decode(&manifest)
}
