name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - uses: denolib/setup-deno@v2
      with:
        deno-version: v1.x

    - name: Build
      run: make

    - name: Test
      run: make test-short
